import auscc as au
import matplotlib.pyplot as plt
print('Simple grounded transmon')
circ1 = au.circuit(nodes=['1'])
circ1.add_branch(start='ground', end='1', type='C', param_key='C')
circ1.add_branch(start='ground', end='1', type='JJ', param_key='E_J')
print(circ1)
H_gen = circ1.SHO_hamiltonian(dims=[3], taylor_order = 4)
print(H_gen({'t':0,'E_J':5,'C':1}),'\n\n')

print('Transmon not grounded')
circ2 = au.circuit(nodes=['1', '2'])
circ2.add_branch(start='1', end='2', type='C', param_key='C')
circ2.add_branch(start='1', end='2', type='JJ', param_key='E_J')
circ2.def_coord([1/2, -1/2])
circ2.def_coord([1/2, 1/2])
print(circ2)
H_gen = circ2.SHO_hamiltonian(dims=[3], taylor_order = 4, eliminate_coords = 1)
print(H_gen({'t':0,'E_J':5,'C':1}),'\n\n')

print('ZZ-coupler')
circ2 = au.circuit(nodes=['1','2','3','4'])
circ2.add_branch(start='1', end='3', type='C', param_key='C')
circ2.add_branch(start='1', end='3', type='JJ', param_key='E_J')
circ2.add_branch(start='3', end='2', type='C', param_key='C')
circ2.add_branch(start='3', end='2', type='JJ', param_key='E_J')
circ2.add_branch(start='2', end='4', type='C', param_key='C')
circ2.add_branch(start='2', end='4', type='JJ', param_key='E_J')
circ2.add_branch(start='4', end='1', type='C', param_key='C')
circ2.add_branch(start='4', end='1', type='JJ', param_key='E_J')
circ2.def_coord([1/2,       -1/2,       0,          0])
circ2.def_coord([0,         0,          1/2,        -1/2])
circ2.def_coord([1/2,       1/2,        -1/2,       -1/2])
circ2.def_coord([1,         1,          1,          1])
print(circ2)
H_gen = circ2.SHO_hamiltonian(dims=[2,2,2], taylor_order = 4, eliminate_coords = [3])
print(au.operator_decomposition(H_gen({'t':0,'E_J':5,'C':1})),'\n\n')
